SELECT PV.ID,
       PV.NUMERO,
       S.NOME BROKER,
       P.NOME CLIENTE,
       F.NOME FILIAL,
       ST.DESCRICAO,
       PG.VALOR_PAGAMENTO VALOR_TOTAL,
       C.NOME CONDICAO_PAGAMENTO,
       C.ID ID_CONDICAO_PGTO,
       CL.ID ID_CLIENTE,
       F.ID ID_FILIAL,
       PG.NUMERO_TRANSACAO,
       PG.DH_APROVACAO DATA_TRANSACAO,
       ps.descricao status_descricao,
       ps.constante status_constante
FROM MKR_HUB_PED_VENDA PV
INNER JOIN MKR_HUB_PED_VENDA_PGTO PG ON PG.ID_HUB_PED_VENDA = PV.ID
INNER JOIN MKR_HUB_COND_PAGAMENTO_PARCELA CP ON CP.ID = PG.ID_HUB_COND_PAG_PARC
INNER JOIN MKR_HUB_COND_PAGAMENTO C ON C.ID = CP.ID_HUB_COND_PAGAMENTO_ORIGEM
INNER JOIN MKR_INTEG_SIS S ON S.ID = C.ID_INTEG_SIS
INNER JOIN MKR_PESSOA P ON P.ID = PV.ID_PESSOA
INNER JOIN MKR_CLIENTE CL ON CL.id_pessoa = PV.id_pessoa
INNER JOIN MKR_FILIAL F ON F.ID = PV.ID_FILIAL
INNER JOIN MKR_HUB_PED_VENDA_STAT_REF SR ON SR.ID = PV.ID_HUB_PED_VENDA_STAT_REF
INNER JOIN MKR_HUB_PED_VENDA_STATUS ST ON ST.ID = SR.ID_HUB_PED_VENDA_STATUS_ORIG
LEFT JOIN MKR_HUB_STATUS_PAGAMENTO ps ON ps.id = pg.id_hub_status_pagamento
WHERE 1= 1