SELECT P.ID ID_PRODUTO,S.ID ID_SKU,PAS.QUANTIDADE_ACESSORIOS, 
PF.ID IS NOT NULL FAVORITO,HCP.ID_HOME_CATALOGO ID_HOME,DP.ID ID_DEPARTAMENTO,DP.DESCRICAO DEPARTAMENTO,
P.CODIGO CODIGO_PRODUTO,S.CODIGO CODIGO_SKU,TD.COR DESTAQUE_COR,
COALESCE(PCS.caracteristica,PCP.caracteristica) caracteristica,
COALESCE(PCS.TITULO,PCP.TITULO) TITULO,
COALESCE(PCS.SOB_MEDIDA,PCP.SOB_MEDIDA) SOB_MEDIDA,
COALESCE(PCS.POSSUI_SPV,PCP.POSSUI_SPV) POSSUI_SPV,
PCS.LINK_VIDEO,
TD.DESCRICAO DESTAQUE_DESCRICAO,TD.CONSTANTE DESTAQUE_CONSTANTE, 
GI.ID_HUB_GRADE,GI.CODIGO CODIGO_GRADE,GI.LEGENDA,SGI.ID_HUB_GRADE_ITEM,PVI.QUANTIDADE,PVI.COMPRIMENTO,PVI.LARGURA, 
CPU.PERCENTUAL_SPV,
CASE WHEN COALESCE(PCS.POSSUI_SPV,PCP.POSSUI_SPV) = TRUE THEN TRUNC(TPI.VALOR_PRECO_VENDA *  CPU.PERCENTUAL_SPV / 100, 2) ELSE 0 END AS VALOR_SPV,
PD.PERCENTUAL_DESCONTO, TRUNC(TPI.VALOR_PRECO_VENDA * PD.PERCENTUAL_DESCONTO / 100, 2) VALOR_DESCONTO,
COALESCE(IMG.URL,'http://icons.iconarchive.com/icons/iconsmind/outline/512/Box-Open-icon.png') AVATAR,
COALESCE(S.DESCRICAO, P.DESCRICAO || ' ' || COALESCE(GI.LEGENDA, '')) DESCRICAO,
COALESCE(S.DESCRICAO, P.DESCRICAO || ' ' || COALESCE(GI.LEGENDA, '')) || ' - ' || COALESCE(S.CODIGO, P.CODIGO)  PESQUISA,
TPI.VALOR_PRECO_VENDA,
(TPI.VALOR_PRECO_VENDA - TRUNC(TPI.VALOR_PRECO_VENDA * COALESCE(PD.PERCENTUAL_DESCONTO,0) / 100, 2)) VALOR,
COALESCE(CS.ID_CLASSIFICACAO, 0) CLASSIFICACAO,COALESCE(CP.ID_CATALOGO, 0) CATALOGO 
FROM MKR_HUB_PRODUTO P
    INNER JOIN MKR_HUB_PRODUTO_SKU S ON (S.ID_HUB_PRODUTO = P.ID)
    INNER JOIN MKR_HUB_PRODUTO_SKU_GRADE_ITEM SGI ON (SGI.ID_HUB_PRODUTO_SKU = S.ID)
    INNER JOIN MKR_HUB_GRADE_ITEM GI ON (GI.ID = SGI.ID_HUB_GRADE_ITEM)
    INNER JOIN MKR_HUB_TABELA_PRECO_ITEM TPI ON (TPI.ID_HUB_PRODUTO_SKU = S.ID)
    INNER JOIN (SELECT CPU.* FROM MKR_CATALOGO_PERFIL CPU, MKR_PERFIL_USUARIO PU 
                WHERE PU.ID_USUARIO = :id_usuario AND PU.ID_PERFIL = CPU.ID_PERFIL) CPU ON (1 = 1)
    LEFT JOIN (SELECT COUNT(*) QUANTIDADE_ACESSORIOS,PAS.ID_PRODUTO FROM MKR_HUB_PRODUTO_ACESSORIO PAS GROUP BY PAS.ID_PRODUTO) PAS ON (PAS.ID_PRODUTO = P.ID)
    INNER JOIN MKR_CATALOGO_PRODUTO CP ON (CP.id_hub_produto = P.ID AND CP.ID_CATALOGO = CPU.ID_CATALOGO)
    LEFT  JOIN MKR_PRODUTO_DESCONTO PD ON (PD.ID_HUB_PRODUTO_SKU = S.ID AND PD.ID_CATALOGO = CP.ID_CATALOGO AND CPU.ID_PERFIL = PD.ID_PERFIL and current_timestamp between pd.data_inicial and pd.data_final)
    LEFT JOIN MKR_HUB_DEPARTAMENTO DP ON (DP.ID = P.ID_HUB_DEPARTAMENTO)
    LEFT JOIN MKR_HOME_CATALOGO_PRODUTO HCP ON (HCP.ID_HUB_PRODUTO_SKU = S.ID)
    LEFT JOIN MKR_HOME_CATALOGO HC ON (HC.ID = HCP.ID_HOME_CATALOGO )
    LEFT JOIN MKR_TIPO_DESTAQUE TD ON (TD.ID = HC.ID_TIPO_DESTAQUE)
    LEFT JOIN (SELECT CS.*,C.DESCRICAO,C.ID_SUPERIOR,O.ID ID_NIVEL_2,O.ID_SUPERIOR ID_NIVEL_3
                FROM MKR_CLASSIFICACAO_PRODUTO CS INNER JOIN MKR_CLASSIFICACAO C ON (C.ID = CS.id_classificacao)
                                                  LEFT JOIN MKR_CLASSIFICACAO O ON (O.ID = C.ID_SUPERIOR)
               ) CS ON (CS.ID_PRODUTO = P.ID AND (CS.ID_CLASSIFICACAO = :classificacao OR CS.ID_SUPERIOR = :classificacao OR CS.ID_NIVEL_2 = :classificacao OR CS.ID_NIVEL_3 = :classificacao))
    LEFT JOIN MKR_PRODUTO_COMPLEMENTO PCS ON (S.ID = PCS.id_hub_produto_sku)
    LEFT JOIN MKR_PRODUTO_COMPLEMENTO PCP ON (P.ID = PCP.id_hub_produto)  
    LEFT JOIN (SELECT * FROM MKR_USUARIO_PRODUTO_FAVORITO PF WHERE PF.ID_USUARIO = :id_usuario) PF ON (S.ID = PF.ID_HUB_PRODUTO_SKU)
    LEFT JOIN (SELECT SUM(PVI.QUANTIDADE) QUANTIDADE,PVI.ID_HUB_PRODUTO_SKU,PIC.COMPRIMENTO,PIC.LARGURA
                 FROM MKR_HUB_PED_VENDA_ITEM PVI,MKR_HUB_PED_VENDA PV,MKR_USUARIO U,MKR_HUB_PED_VENDA_ITEM_COMPL PIC
               WHERE PV.ID = PVI.ID_HUB_PED_VENDA AND PV.ID_VENDEDOR= U.ID_PESSOA AND U.ID = :id_usuario AND PIC.ID_HUB_PEDIDO_VENDA_ITEM = PVI.ID and PV.id_hub_ped_venda_stat_ref  = 7 
              GROUP BY PVI.ID_HUB_PRODUTO_SKU,PIC.COMPRIMENTO,PIC.LARGURA) PVI ON (PVI.ID_HUB_PRODUTO_SKU = S.ID)
    LEFT JOIN LATERAL (
SELECT IMG.*,TM.ORDEM FROM (
SELECT S.ID ID_SKU,P.ID ID_PRODUTO,COALESCE(SM.ENDERECO,SP.ENDERECO) URL,COALESCE(SM.ID_HUB_PRODUTO_TIPO_MIDIA,SP.ID_HUB_PRODUTO_TIPO_MIDIA) ID_TIPO FROM 
MKR_HUB_PRODUTO_SKU S INNER JOIN MKR_HUB_PRODUTO P ON P.ID = S.ID_HUB_PRODUTO
LEFT JOIN MKR_HUB_PRODUTO_SKU_MIDIA SM ON SM.ID_HUB_PRODUTO_SKU = S.ID
LEFT JOIN MKR_HUB_PRODUTO_MIDIA SP ON SP.ID_HUB_PRODUTO = P.ID 
) IMG , MKR_HUB_PRODUTO_TIPO_MIDIA TM
WHERE IMG.URL IS NOT NULL AND TM.ID = IMG.ID_TIPO AND TM.IDENTIFICADOR IN ('CAPA','IMAGEM') AND S.ID = IMG.ID_SKU
ORDER BY TM.ORDEM ASC
LIMIT 1
) IMG ON 1 = 1
WHERE 1 = 1 AND ((CS.ID_CLASSIFICACAO = :classificacao OR CS.ID_SUPERIOR = :classificacao OR CS.ID_NIVEL_2 = :classificacao OR CS.ID_NIVEL_3 = :classificacao) OR COALESCE(:classificacao,0) = 0)
AND 1 = 1 AND P.ativo = true